const globals = require('../globals.js');

// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('acceptEULA', function() {
  this.timeout(30000)
  let driver
  let vars
  before(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer(globals.webDriverUrl).build()
    vars = {}
  })
  after(async function() {
    await driver.quit();
  })
  it('launch app', async function() {
    await driver.get(globals.appRoute)
  })
  it('accept EULA', async function() {
    await driver.findElement(By.css(".pf-m-display-lg")).click()
  })
  it('assert we land on profile page', async function() {
    assert(await driver.getTitle() == "COVIDsafe | Profile")
  })
})
