const globals = require('../test_resources/globals.js')

// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test Contact Link', function() {
  this.timeout(30000)
  let driver
  let vars
  before(async function() {
    driver = await new Builder().forBrowser(globals.browser).usingServer(globals.webDriverUrl).build()
    vars = {}
  })
  after(async function() {
    await driver.quit();
  })
  it('Launch app', async function() {
    await driver.get(globals.appRoute)
  })
  it('Click contact link', async function() {
    await driver.findElement(By.css(".pf-c-nav__item:nth-child(1) span")).click()
  })
  it('Assert we landed on Contact page', async function() {
    assert(await driver.getCurrentUrl() == globals.appRoute + "/contact")
  })
})
